# Generated by Django 4.2.17 on 2025-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('cafe_space_position', models.CharField(choices=[('window', 'Near Window'), ('door', 'Near Door'), ('corner', 'In Corner'), ('center', 'Center of Cafe'), ('outdoor', 'Outdoor'), ('bar', 'Near Bar'), ('private', 'Private Room')], max_length=20)),
            ],
        ),
    ]
