<<<<<<< HEAD
# Generated by Django 4.2.17 on 2025-01-23 05:58
=======
# Generated by Django 4.2 on 2025-01-23 08:08
>>>>>>> 35523a58023033afc464c4cab356be9d8d11e507

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(choices=[('Pastries', 'Pastries'), ('icecream', 'Ice cream'), ('Soups', 'Soups'), ('Salads', 'Salads'), ('hotdrinks', 'Hot drinks'), ('colddrinks', 'cold drinks')], default='null', max_length=50)),
=======
                ('name', models.CharField(default='null', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
>>>>>>> 35523a58023033afc464c4cab356be9d8d11e507
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the menu item (minimum 2 characters).', max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price', models.BigIntegerField(help_text='Price of the item in decimal format.')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount as a decimal value (e.g., 0.15 for 15%).', max_digits=4, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the menu item.')),
                ('serving_time_start', models.TimeField()),
                ('serving_time_end', models.TimeField()),
                ('estimated_cooking_time', models.CharField(choices=[('10 min', '10 min'), ('20 min', '20 min'), ('30 min', '30 min')], default='null', help_text='Estimated time to prepare the dish.', max_length=50)),
                ('entity', models.SmallIntegerField(help_text='Number of items available.')),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('category', models.ForeignKey(help_text='Category to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu_items.category')),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_items.menuitem')),
            ],
        ),
=======
>>>>>>> 35523a58023033afc464c4cab356be9d8d11e507
    ]
