# Generated by Django 4.2.17 on 2025-02-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
