# Generated by Django 4.2.17 on 2025-02-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0004_remove_comment_comments_comment_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='bulk_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='bulk_discount_treshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
