# Generated by Django 4.2.17 on 2025-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0005_rename_discount_menuitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='bulk_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='bulk_discount_treshold',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_stock',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.IntegerField(choices=[(0, '0%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0),
        ),
    ]
