# Generated by Django 4.2.17 on 2025-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0006_remove_menuitem_bulk_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='discount_stock',
            field=models.IntegerField(default=0),
        ),
    ]
