# Generated by Django 4.2.17 on 2025-01-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
