# Generated by Django 4.2 on 2025-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status_R',
            field=models.BooleanField(default=False),
        ),
    ]
