# Generated by Django 4.2.17 on 2025-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('is_refunded', models.BooleanField(default=False)),
                ('order', models.CharField(max_length=50)),
                ('status_R', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
