# Generated by Django 4.2 on 2025-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_receipt_status_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_R',
            field=models.CharField(max_length=50),
        ),
    ]
