# Generated by Django 4.2.17 on 2025-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='item_origin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
